destination: ./_site
source:      ./www
auto:        false
lsi:         false
server_port: 4000
pygments:    true
markdown:    maruku
permalink:   date
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
# JRuby-specific info here; goes into the "site" jekyll variable
release:
  url: /2011/10/25/jruby-1-6-5
  version: 1.6.5
  tar: http://jruby.org.s3.amazonaws.com/downloads/1.6.5/jruby-bin-1.6.5.tar.gz
  zip: http://jruby.org.s3.amazonaws.com/downloads/1.6.5/jruby-bin-1.6.5.zip
  exe: http://jruby.org.s3.amazonaws.com/downloads/1.6.5/jruby_windows_1_6_5.exe
  exe64: http://jruby.org.s3.amazonaws.com/downloads/1.6.5/jruby_windows_x64_1_6_5.exe
  exejre: http://jruby.org.s3.amazonaws.com/downloads/1.6.5/jruby_windowsjre_1_6_5.exe
  exejre64: http://jruby.org.s3.amazonaws.com/downloads/1.6.5/jruby_windows_x64_jre_1_6_5.exe
  dmg: http://jruby.org.s3.amazonaws.com/downloads/1.6.5/JRuby-1.6.5.dmg
urls:
  s3: http://jruby.org.s3.amazonaws.com/downloads
  tryjruby: http://jruby.org.s3.amazonaws.com/tryjruby
  jira: http://jira.codehaus.org/browse/JRUBY
  wiki: http://wiki.jruby.org/
  lists: http://wiki.jruby.org/MailingLists
team_email: team@jruby.org
domain: www.jruby.org
