destination: ./_site
auto:        false
lsi:         false
server_port: 4000
highlighter: rouge
markdown:    kramdown
permalink:   date
# JRuby-specific info here; goes into the "site" jekyll variable
release:
  url: /2018/11/13/jruby-9-2-4-0.html
  version: 9.2.4.0
  tar: https://repo1.maven.org/maven2/org/jruby/jruby-dist/9.2.4.0/jruby-dist-9.2.4.0-bin.tar.gz
  zip: https://repo1.maven.org/maven2/org/jruby/jruby-dist/9.2.4.0/jruby-dist-9.2.4.0-bin.zip
  exe: https://s3.amazonaws.com/jruby.org/downloads/9.2.4.0/jruby_windows_9_2_4_0.exe
  exe64: https://s3.amazonaws.com/jruby.org/downloads/9.2.4.0/jruby_windows_x64_9_2_4_0.exe
  gem: https://rubygems.org/gems/jruby-jars/versions/9.2.4.0
urls:
  maven: https://repo1.maven.org/maven2/org/jruby
  s3: https://s3.amazonaws.com/jruby.org/downloads
  tryjruby: https://s3.amazonaws.com/jruby.org/tryjruby
  bugs: http://github.com/jruby/jruby/issues
  jira: http://jira.codehaus.org/browse/JRUBY
  wiki: http://wiki.jruby.org/
  lists: http://wiki.jruby.org/MailingLists
  github: https://github.com/jruby/jruby
team_email: team@jruby.org
domain: www.jruby.org
